version: '3.7'

services:
  smalls:
    network_mode: host
    container_name: apismalls
    build: APISMALLS/.
    ports:
      - "5000:5000"
  database:
    network_mode: host
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_DB:main 
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    ports:
      - 5432:5432
  orders:
    network_mode: host
    container_name: orders 
    build: gPRC_smalls/.
    expose:
      - 50051
    ports:
      - 50051:50051