# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders_types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orders_types.proto',
  package='orders',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12orders_types.proto\x12\x06orders\"\'\n\x05Order\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\r\"4\n\x12\x43reateOrderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\r\"1\n\x11\x43reateOrderResult\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Order\"0\n\x10GetOrdersRequest\x12\x1c\n\x05order\x18\x01 \x03(\x0b\x32\r.orders.Order\"/\n\x0fGetOrdersResult\x12\x1c\n\x05order\x18\x01 \x01(\x0b\x32\r.orders.Orderb\x06proto3'
)




_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='orders.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='orders.Order.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='orders.Order.quantity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=69,
)


_CREATEORDERREQUEST = _descriptor.Descriptor(
  name='CreateOrderRequest',
  full_name='orders.CreateOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='orders.CreateOrderRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='orders.CreateOrderRequest.quantity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=123,
)


_CREATEORDERRESULT = _descriptor.Descriptor(
  name='CreateOrderResult',
  full_name='orders.CreateOrderResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='orders.CreateOrderResult.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=174,
)


_GETORDERSREQUEST = _descriptor.Descriptor(
  name='GetOrdersRequest',
  full_name='orders.GetOrdersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='orders.GetOrdersRequest.order', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=224,
)


_GETORDERSRESULT = _descriptor.Descriptor(
  name='GetOrdersResult',
  full_name='orders.GetOrdersResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='orders.GetOrdersResult.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=273,
)

_CREATEORDERRESULT.fields_by_name['order'].message_type = _ORDER
_GETORDERSREQUEST.fields_by_name['order'].message_type = _ORDER
_GETORDERSRESULT.fields_by_name['order'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['CreateOrderRequest'] = _CREATEORDERREQUEST
DESCRIPTOR.message_types_by_name['CreateOrderResult'] = _CREATEORDERRESULT
DESCRIPTOR.message_types_by_name['GetOrdersRequest'] = _GETORDERSREQUEST
DESCRIPTOR.message_types_by_name['GetOrdersResult'] = _GETORDERSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'orders_types_pb2'
  # @@protoc_insertion_point(class_scope:orders.Order)
  })
_sym_db.RegisterMessage(Order)

CreateOrderRequest = _reflection.GeneratedProtocolMessageType('CreateOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERREQUEST,
  '__module__' : 'orders_types_pb2'
  # @@protoc_insertion_point(class_scope:orders.CreateOrderRequest)
  })
_sym_db.RegisterMessage(CreateOrderRequest)

CreateOrderResult = _reflection.GeneratedProtocolMessageType('CreateOrderResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERRESULT,
  '__module__' : 'orders_types_pb2'
  # @@protoc_insertion_point(class_scope:orders.CreateOrderResult)
  })
_sym_db.RegisterMessage(CreateOrderResult)

GetOrdersRequest = _reflection.GeneratedProtocolMessageType('GetOrdersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERSREQUEST,
  '__module__' : 'orders_types_pb2'
  # @@protoc_insertion_point(class_scope:orders.GetOrdersRequest)
  })
_sym_db.RegisterMessage(GetOrdersRequest)

GetOrdersResult = _reflection.GeneratedProtocolMessageType('GetOrdersResult', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERSRESULT,
  '__module__' : 'orders_types_pb2'
  # @@protoc_insertion_point(class_scope:orders.GetOrdersResult)
  })
_sym_db.RegisterMessage(GetOrdersResult)


# @@protoc_insertion_point(module_scope)
